### PR TITLE
Bump API version to 3.0.0-ALPHA12 (NOT TESTED)

### PR DESCRIPTION
**Pull request by XuPaperCup**

### CODE REVIEW

**Comment by SOF3** [comment]
Why do you create it if it isn't tested?

**Comment by XuPaperCup** [comment]
Sorry,but I don't create it ,I can't test.(Because I don't know how to create phar...)

**Comment by XuPaperCup** [comment]
I just tested and it OK.

**Comment by XuPaperCup** [comment]
But I find a bug is that when I delete a plugin,it said deleted but when I check the file,it didn't delete...

**Comment by XuPaperCup** [comment]
Can you help to fix it?

**Pull request closed without merging**
