### PR TITLE
Tiny changes made to enhance stability and expand API version support.

### PR DESCRIPTION
**Pull request by Zachari**
# Changelog
- **Update: Added API Versions [[plugin.yml](https://github.com/Zachari/Sheep/blob/master/plugin.yml)]:** Updated to support 3.0.0-ALPHA6 and 3.0.0-ALPHA7.
- **Minor Fix [[/src/Sheep/Command/PMCommandProxy.php](https://github.com/Zachari/Sheep/blob/master/src/Sheep/Command/PMCommandProxy.php)]:** Added string type to $commandLabel in execute method parameters to prevent server crash due to a mismatch with function declaration for pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, string $commandLabel, array $args).
- **Minor Fix [[/src/Sheep/Utils/ScanTask.php](https://github.com/Zachari/Sheep/blob/master/src/Sheep/Utils/ScanTask.php)]:** Added int type to $currentTick in onRun method parameters to prevent server crash due to a mismatch with function declaration for pocketmine\scheduler\Task::onRun(int $currentTick).

### CODE REVIEW

**Comment by SOF3** [comment]
You should remove the older API versions.

**Comment by KnownUnown** [comment]
Thanks for the PR! It looks good functionality-wise, but you messed with the Travis build (specifically the checker gist, which I'm planning to put in the repo in the future) and README. Mind reverting these changes?

**Comment by KnownUnown** [comment]
API bumped in https://github.com/KnownUnown/Sheep/commit/5c2df0c67ca3aaf83c67994fb9c9142f061d4c4d

**Comment by Zachari** [comment]
Sorry about that. My submission was a late-night, sleepless one, and in that state, I didn't realize that I was using my experimental branch. That's sloppy on my part.  I've been in crunch for a client and kept saying I'd come back to this but didn't. Any future activity on my part will be handled with a bit more professionalism. So, once again, my apologies on that front.

That said, the current build implements the above fixes. Great work.

**Pull request closed without merging**
